# Generated by Django 5.0.6 on 2024-06-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_subcategory_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_manage_products', 'Can manage products')]},
        ),
        migrations.AddField(
            model_name='customer',
            name='is_product_manager',
            field=models.BooleanField(default=False),
        ),
    ]
