# Generated by Django 5.0.6 on 2024-06-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_options_customer_is_product_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_product_manager',
        ),
    ]
