# Generated by Django 5.0.6 on 2024-06-12 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_price_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='total_price',
        ),
    ]
