# Generated by Django 5.0.6 on 2024-06-12 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_price_order_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_price',
            new_name='price',
        ),
    ]
